spring.application.name=YourChoiceShop
# Server Port
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=YourChoiceShopDB;encrypt=true;trustServerCertificate=true;loginTimeout=30;socketTimeout=30000
spring.datasource.username=sa
spring.datasource.password=123456

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==============================================================
# 2. JPA / HIBERNATE
# ==============================================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# 3. FILE UPLOAD CONFIG (Quan trọng để up ảnh)
# ==============================================================
spring.servlet.multipart.enabled=true
# Cho phép file to thoải mái (100MB)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ==============================================================
# 4. SERVER TUNING (Fix lỗi 500 khi submit form to)
# ==============================================================
# Tomcat đếm số lượng tham số, đặt -1 để nó KHÔNG ĐẾM NỮA
server.tomcat.max-parameter-count=-1
# Cho phép Post dữ liệu to
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1

# ==============================================================
# 5. EMAIL CONFIGURATION (SMTP Gmail)
# ==============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duongductungtn2005@gmail.com
# Mật khẩu ứng dụng 16 ký tự
spring.mail.password=rsfn oshc ccbs gvni

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Timeout settings (Giúp app không bị treo nếu mạng lag)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000

spring.mail.properties.mail.smtp.writetimeout=5000



