spring.application.name=YourChoiceShop
# Server Port
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=YourChoiceShopDB;encrypt=true;trustServerCertificate=true;loginTimeout=30;socketTimeout=30000
spring.datasource.username=sa
spring.datasource.password=123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==============================================================
# 2. JPA / HIBERNATE
# ==============================================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# 3. FILE UPLOAD CONFIG (Quan tr\u1ecdng \u0111\u1ec3 up \u1ea3nh)
# ==============================================================
spring.servlet.multipart.enabled=true
# Cho ph\u00e9p file to tho\u1ea3i m\u00e1i (100MB)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ==============================================================
# 4. SERVER TUNING (Fix l\u1ed7i 500 khi submit form to)
# ==============================================================
# Tomcat \u0111\u1ebfm s\u1ed1 l\u01b0\u1ee3ng tham s\u1ed1, \u0111\u1eb7t -1 \u0111\u1ec3 n\u00f3 KH\u00d4NG \u0110\u1ebeM N\u1eeeA
server.tomcat.max-parameter-count=-1
# Cho ph\u00e9p Post d\u1eef li\u1ec7u to
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1

# ==============================================================
# 5. EMAIL CONFIGURATION (SMTP Gmail)
# ==============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duongductungtn2005@gmail.com
# M\u1eadt kh\u1ea9u \u1ee9ng d\u1ee5ng 16 k\u00fd t\u1ef1
spring.mail.password=rsfn oshc ccbs gvni

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Timeout settings (Gi\u00fap app kh\u00f4ng b\u1ecb treo n\u1ebfu m\u1ea1ng lag)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000

spring.mail.properties.mail.smtp.writetimeout=5000

# Ph\u00ed v\u1eadn chuy\u1ec3n GHN
ghn.token=ca1ca398-1aa1-11f1-afba-f237094374aa
ghn.shop-id=6310460
ghn.base-url=https://online-gateway.ghn.vn
ghn.from-district-id=3440
ghn.from-ward-code=13007
